live_config_reload = true

[[indexed_colors]]
color = "0xff9e64"
index = 16

[[indexed_colors]]
color = "0xdb4b4b"
index = 17

[bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.offset]
x = 0
y = 0

[normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[window]
dynamic_padding = false
opacity = 1.0

[window.padding]
x = 0
y = 0
