live_config_reload = true

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
dynamic_padding = false
opacity = 1.0
decorations = "None"

[window.padding]
x = 0
y = 0
